services:
  lgweb:
    build:
      context: ../
      dockerfile: docker/web.dockerfile
    restart: always
    ports:
      - "${WEB_PORT:-5000}:5000"
    container_name: lgweb
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_MAX_DAYS=${NEXT_PUBLIC_MAX_DAYS}
      - SESSION_PASSWORD=${SESSION_PASSWORD}
      - PORT=${NEXT_PORT}
    depends_on:
      - lgapi
    networks:
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lgweb.rule=PathPrefix(`/lgweb`)"
      - "traefik.http.routers.lgweb.entrypoints=web"
      - "traefik.http.services.lgweb.loadbalancer.server.port=5000"


  lgapi:
    build:
      context: ../
      dockerfile: docker/api.dockerfile
    restart: always
    ports:
      - "${API_PORT:-5005}:5005"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_PRIMARY_URL=${MYSQL_PRIMARY_URL}
      - BASE_URL=${BASE_URL}
      - ACCESS_TOKEN_EXPIRED_TIME=10m
      - REFESH_TOKEN_EXPIRED_TIME=1h
      - APP_PORT=5000
      - APP_ADDRESS=lgapi
      - AUTO_MIGRATION=true
      - NODE_OPTIONS="--max_old_space_size=3072"
    container_name: lgapi
    networks:
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lgapi.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.lgapi.entrypoints=web"
      - "traefik.http.services.lgapi.loadbalancer.server.port=5005"

networks:
  app_net:
    external: true
